export enum Events {
	PROJECTILE_CHANGED = "PROJECTILE_CHANGED",
	PROJECTILE_FIRED = "PROJECTILE_FIRED",
	PROJECTILE_STOPPED = "PROJECTILE_STOPPED",
	PROJECTILE_DESTROYED = "PROJECTILE_DESTROYED",
	COIN_POCKETED = "COIN_POCKETED",
	POWERUP_USE = "POWERUP_USE",
	POWERUP_DISABLE = "POWERUP_DISABLE"
}
